import express from "express";
import path from "path";
import getDirname from "./utilities/get-dirname.js";
import * as config from "./configs/main.js";
const __dirname = getDirname(import.meta.url);
const app = express();
app.use(express.static(path.join(__dirname, "../public")));
app.set("view engine", "ejs");
app.set("views", path.join(__dirname, "./views"));
import contentPage from "./controllers/content-page.js";
contentPage.run(app);
app.listen(config.port, () => console.log(`  ===  http://localhost:${config.port}  ===`));
